name: beatbrows
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  provider: ^6.0.0
  flutter_soloud: ^2.0.0
  shared_preferences: ^2.3.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.8

flutter:
  uses-material-design: true
  assets:
    - assets/word.json
    - assets/backgound_music.mp3
    - assets/pop_sound.mp3

flutter_launcher_icons:
  android: "lancher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_logo.png"